name: Build

on:
  push:
    branches:
      - main
      - deploy
      - master


jobs:
  sonar:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: mvn clean install

      - name: Sonar Scan
        run: |
          mvn sonar:sonar \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=spring-sonar-demo -Dsonar.projectName='spring-sonar-demo'
